import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { NavbarComponent } from "./components/NavbarComponent";
import { FooterComponent } from "./components/FooterComponent";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-black text-gray-200">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          {/* Navbar */}
          <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 mt-16">
            <NavbarComponent/>
          </div>

          {/* Pages */}
          <main className="min-h-screen">{children}</main>

          {/* Footer */}
          <FooterComponent/>
      </body>
    </html>
  );
}
